### ISSUE TITLE
How to deal with adata.X being a sparse matrix?

### ISSUE THREAD

**Issue by lwtan90** [Szym29/ZeroInflatedNegativeBinomial_VAE#1]
Hi,

This is really helpful! Thank you!!
By the way, I am assuming that adata is an AnnData object from the Scanpy, and adata.X is actually a sparse matrix object. Do you recommend converting it to a numpy array prior to creating the dataloader object?
Thank you.

Wilson

**Comment by Szym29** [comment]
Hi, 

You can use `adata.X = adata.X.toarray()` to transform the sparse matrix to a dense np.array before creating the dataloader object. I will also update the script this weekend to provide a customized h5adDataset object that you can directly pass the data to this function. 

Cheers,
Yumin

**Comment by Szym29** [comment]
Hi @lwtan90, 

I have updated my code. You should be able to run the model on your data.
